### PR TITLE
update to latest selenium and chrome drivers

### PR DESCRIPTION
**Pull request by mobify-derrick**
Status: **Ready for Review**
Owner: @mobify-derrick
Reviewers: @ellenmobify @marlowpayne @mikenikles 

## Changes
- Update Selenium Version to 2.52.0
- Update ChromeDriver to 2.21

## Todos:
- [x] Passed linting check (run `grunt lint`)
- [x] Updated README
- [x] Updated CHANGELOG

### Feedback:
_none so far_

## How To Test
- Checkout this branch
- `npm install`
- `npm link`
- `grunt lint`

### CODE REVIEW

**Comment by marlowpayne** [comment]
Looking good. I'll hold off on a +1 until I've tested it integrated into an existing project.

**Comment by mobify-derrick** [comment]
Ran tests on project. No issues to report

**Comment by ellenmobify** [comment]
:+1: tried running tests using this branch, all went well.

**Comment by marlowpayne** [comment]
:+1: LGTM

**Pull request merged**
