### PR TITLE
Update Selenium and Chrome Drivers

### PR DESCRIPTION
**Pull request by mobify-derrick**
Update Selenium and Chrome Drivers

Status: **Opened for review**
Reviewers: ** @ellenmobify @marlowpayne @johnboxall  **

## Changes
- Set seleniumVersion to 2.48.2
- Set chromeDriverVersion 2.20

## Checklist
- [x] QA+1
- [x] Eng +1

## How to Test
- Clone a repo with Nightwatch System tests (eg. Matalan)
- In project root package.json point the nightwatch-commands package to "git://github.com/mobify/nightwatch-commands.git#update-selenium-chrome-drivers"
- run `npm install` in terminal for the project
- run `grunt nightwatch -e mobile --tag conversion --retries 1` to run tests (for Matalan only)

### CODE REVIEW

**Comment by ellenmobify** [comment]
:+1: will also have to update the package version in `package.json`

**Comment by marlowpayne** [comment]
:+1: once nightwatch-command's `package.json` is updated to prep a new npm release.

**Comment by marlowpayne** [comment]
:+1:

**Comment by ellenmobify** [comment]
:+1:

**Pull request merged**
